CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255),
    person_id VARCHAR(12) NOT NULL UNIQUE,
    gender VARCHAR(50),
    uuid VARCHAR(36) NOT NULL UNIQUE
);
